<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Tigersun\\Interview\\Contracts\\CurrencyCalculatorInterface' => 'get1',
  'subEntry1' => 'get2',
  'Tigersun\\Interview\\Contracts\\CurrencyRateInterface' => 'get3',
);

    protected function get2()
    {
        return $this->delegateContainer->get('Tigersun\\Interview\\Contracts\\CurrencyRateInterface');
    }

    protected function get1()
    {
        $object = new Tigersun\Interview\CurrencyCalculator($this->get2());
        return $object;
    }

    protected function get3()
    {
        $object = new Tigersun\Interview\CurrencyRateFinder();
        return $object;
    }

}
